#!/usr/bin/env python3
"""Run the input pipeline with optional deterministic intent ranking."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    from tools.candidate_gates import build_gate_report
    from tools.candidate_selection import INTENT_ALGORITHM, build_selection, intent_sha256, normalize_intent
    from tools.candidate_space import build_candidate_space, canonical_json
    from tools.consumer import import_signals
    from tools.proposition_provenance import build_provenance
    from tools.signal_bundle import validate_signal_bundle
    from tools.validate import ROOT, load_yaml
except ModuleNotFoundError:  # pragma: no cover - direct CLI fallback
    ROOT = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(ROOT))
    from tools.candidate_gates import build_gate_report
    from tools.candidate_selection import INTENT_ALGORITHM, build_selection, intent_sha256, normalize_intent
    from tools.candidate_space import build_candidate_space, canonical_json
    from tools.consumer import import_signals
    from tools.proposition_provenance import build_provenance
    from tools.signal_bundle import validate_signal_bundle
    from tools.validate import load_yaml


DEFAULT_RULES_PATH = ROOT / "config/transformation-rules.yaml"
DEFAULT_OUTPUT_PATH = ROOT / "data/run.json"


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected an object")
    return value


def run(
    bundle: dict[str, Any],
    *,
    project_id: str,
    seed_input: str,
    selection_limit: int = 1,
    intent: str | None = None,
    rules: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run all synchronous stages and expose only an opaque intent digest."""
    errors = validate_signal_bundle(bundle)
    if errors:
        raise ValueError("\n".join(errors))
    signals = bundle["records"]
    imported = import_signals(signals)
    registry = rules if rules is not None else load_yaml(DEFAULT_RULES_PATH)
    candidate_space = build_candidate_space(signals, registry, "run.candidates")
    gate_report = build_gate_report(candidate_space, signals, registry, "run.gates")
    selection = build_selection(
        candidate_space,
        gate_report,
        project_id,
        seed_input,
        selection_limit,
        "run.selection",
        signals=signals if intent is not None else None,
        intent=intent,
    )
    provenance = build_provenance(selection, candidate_space, gate_report, signals, registry, "run.provenance")
    result: dict[str, Any] = {
        "bundle": bundle,
        "consumer_package": imported,
        "candidate_space": candidate_space,
        "gate_report": gate_report,
        "selection": selection,
        "provenance": provenance,
    }
    if intent is not None:
        # Normalize and hash only at the boundary. The supplied text is never
        # copied into the result, logs, provenance, or Git artifacts.
        normalized = normalize_intent(intent, "run.intent")
        result["intent_sha256"] = intent_sha256(normalized)
        result["intent_algorithm"] = INTENT_ALGORITHM
    return result


def _render(data: dict[str, Any]) -> bytes:
    return (canonical_json(data) + "\n").encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", type=Path, required=True)
    parser.add_argument("--project-id", required=True)
    parser.add_argument("--seed-input", required=True)
    parser.add_argument("--selection-limit", type=int, default=1)
    parser.add_argument("--intent")
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--check", action="store_true", help="compare generated bytes without writing")
    args = parser.parse_args()
    try:
        result = run(
            _load_json(args.bundle),
            project_id=args.project_id,
            seed_input=args.seed_input,
            selection_limit=args.selection_limit,
            intent=args.intent,
            rules=load_yaml(args.rules),
        )
    except (OSError, TypeError, ValueError, KeyError) as exc:
        # Validation errors intentionally do not interpolate the raw intent.
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    rendered = _render(result)
    if args.check:
        try:
            observed = args.output.read_bytes()
        except OSError as exc:
            print(f"ERROR: {args.output}: {exc}; remediation: generate the run artifact first", file=sys.stderr)
            return 1
        if observed != rendered:
            print(f"ERROR: {args.output}: generated run bytes differ; remediation: regenerate the deterministic run artifact", file=sys.stderr)
            return 1
        changed = False
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        changed = args.output.exists() and args.output.read_bytes() == rendered
        if not changed:
            args.output.write_bytes(rendered)
    summary = {
        "changed": not changed if not args.check else False,
        "command": "run",
        "selected_count": result["selection"]["selected_count"],
        "status": "PASSED",
    }
    if "intent_sha256" in result:
        summary["intent_algorithm"] = result["intent_algorithm"]
        summary["intent_sha256"] = result["intent_sha256"]
    print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
